# Generated by Django 4.2.27 on 2025-12-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        ("guests", "0001_initial"),
        ("properties", "0001_initial"),
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="check-in time"
                    ),
                ),
                (
                    "expected_check_out",
                    models.DateField(verbose_name="expected check-out"),
                ),
                (
                    "id_type",
                    models.CharField(blank=True, max_length=50, verbose_name="ID type"),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID number"
                    ),
                ),
                (
                    "id_expiry",
                    models.DateField(blank=True, null=True, verbose_name="ID expiry"),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="registration number"
                    ),
                ),
                (
                    "registration_card",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="registration_cards/",
                        verbose_name="registration card",
                    ),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures/",
                        verbose_name="signature",
                    ),
                ),
                (
                    "key_card_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="key card number"
                    ),
                ),
                (
                    "keys_issued",
                    models.PositiveIntegerField(default=1, verbose_name="keys issued"),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="deposit amount",
                    ),
                ),
                (
                    "deposit_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="deposit method"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_check_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_ins",
                        to="guests.guest",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_ins",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "check-in",
                "verbose_name_plural": "check-ins",
                "ordering": ["-check_in_time"],
            },
        ),
        migrations.CreateModel(
            name="WalkIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="phone")),
                ("check_in_date", models.DateField(verbose_name="check-in date")),
                ("check_out_date", models.DateField(verbose_name="check-out date")),
                (
                    "adults",
                    models.PositiveIntegerField(default=1, verbose_name="adults"),
                ),
                (
                    "children",
                    models.PositiveIntegerField(default=0, verbose_name="children"),
                ),
                (
                    "rate_per_night",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="rate per night"
                    ),
                ),
                (
                    "is_converted",
                    models.BooleanField(
                        default=False, verbose_name="converted to reservation"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walk_ins",
                        to="properties.property",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="walk_in",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="walk_ins",
                        to="rooms.roomtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "walk-in",
                "verbose_name_plural": "walk-ins",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=200, verbose_name="reason")),
                (
                    "move_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="move time"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_moves",
                        to="frontdesk.checkin",
                    ),
                ),
                (
                    "from_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_from",
                        to="rooms.room",
                    ),
                ),
                (
                    "moved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_to",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "room move",
                "verbose_name_plural": "room moves",
                "ordering": ["-move_time"],
            },
        ),
        migrations.CreateModel(
            name="GuestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("PHONE", "Phone Message"),
                            ("PACKAGE", "Package"),
                            ("FAX", "Fax"),
                            ("VISITOR", "Visitor"),
                            ("OTHER", "Other"),
                        ],
                        default="PHONE",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "from_name",
                    models.CharField(blank=True, max_length=200, verbose_name="from"),
                ),
                (
                    "from_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contact"
                    ),
                ),
                (
                    "is_delivered",
                    models.BooleanField(default=False, verbose_name="delivered"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="frontdesk.checkin",
                    ),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "guest message",
                "verbose_name_plural": "guest messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="check-out time"
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total charges",
                    ),
                ),
                (
                    "total_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total payments",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="balance",
                    ),
                ),
                (
                    "keys_returned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="keys returned"
                    ),
                ),
                (
                    "is_express",
                    models.BooleanField(default=False, verbose_name="express checkout"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="rating"
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="feedback")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "check_in",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_out",
                        to="frontdesk.checkin",
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_check_outs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "check-out",
                "verbose_name_plural": "check-outs",
                "ordering": ["-check_out_time"],
            },
        ),
    ]
