# Generated by Django 4.2.27 on 2025-12-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        ("rates", "0001_initial"),
        ("guests", "0001_initial"),
        ("channels", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="group name")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="group code"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=200, verbose_name="contact name"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="contact email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="contact phone"
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="check-in date")),
                ("check_out_date", models.DateField(verbose_name="check-out date")),
                (
                    "cutoff_date",
                    models.DateField(blank=True, null=True, verbose_name="cutoff date"),
                ),
                (
                    "rooms_blocked",
                    models.PositiveIntegerField(
                        default=0, verbose_name="rooms blocked"
                    ),
                ),
                (
                    "rooms_picked_up",
                    models.PositiveIntegerField(
                        default=0, verbose_name="rooms picked up"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TENTATIVE", "Tentative"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="TENTATIVE",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "group_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="group rate",
                    ),
                ),
                (
                    "deposit_required",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="deposit required",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_bookings",
                        to="guests.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_bookings",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "group booking",
                "verbose_name_plural": "group bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirmation_number",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="confirmation number",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from OTA or channel manager",
                        max_length=100,
                        verbose_name="external ID",
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="check-in date")),
                ("check_out_date", models.DateField(verbose_name="check-out date")),
                (
                    "arrival_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="arrival time"
                    ),
                ),
                (
                    "departure_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="departure time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CHECKED_IN", "Checked In"),
                            ("CHECKED_OUT", "Checked Out"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("WAITLIST", "Waitlist"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct Booking"),
                            ("PHONE", "Phone"),
                            ("EMAIL", "Email"),
                            ("WALK_IN", "Walk-in"),
                            ("WEBSITE", "Website"),
                            ("OTA", "OTA"),
                            ("GDS", "GDS"),
                            ("CORPORATE", "Corporate"),
                            ("TRAVEL_AGENT", "Travel Agent"),
                        ],
                        default="DIRECT",
                        max_length=20,
                        verbose_name="booking source",
                    ),
                ),
                (
                    "adults",
                    models.PositiveIntegerField(default=1, verbose_name="adults"),
                ),
                (
                    "children",
                    models.PositiveIntegerField(default=0, verbose_name="children"),
                ),
                (
                    "infants",
                    models.PositiveIntegerField(default=0, verbose_name="infants"),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="special requests"),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="internal notes"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total amount",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="deposit amount",
                    ),
                ),
                (
                    "deposit_paid",
                    models.BooleanField(default=False, verbose_name="deposit paid"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="channels.channel",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="guests.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="reservations.groupbooking",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="guests.guest",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="properties.property",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rate_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="rates.rateplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "reservation",
                "verbose_name_plural": "reservations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="rate per night",
                    ),
                ),
                (
                    "total_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="total rate",
                    ),
                ),
                (
                    "adults",
                    models.PositiveIntegerField(default=1, verbose_name="adults"),
                ),
                (
                    "children",
                    models.PositiveIntegerField(default=0, verbose_name="children"),
                ),
                (
                    "guest_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="guest name"
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation_rooms",
                        to="rooms.room",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_rooms",
                        to="rooms.roomtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "reservation room",
                "verbose_name_plural": "reservation rooms",
            },
        ),
        migrations.CreateModel(
            name="ReservationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="action")),
                ("old_value", models.TextField(blank=True, verbose_name="old value")),
                ("new_value", models.TextField(blank=True, verbose_name="new value")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reservation log",
                "verbose_name_plural": "reservation logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ReservationRateDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="rate"
                    ),
                ),
                (
                    "reservation_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_details",
                        to="reservations.reservationroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "reservation rate detail",
                "verbose_name_plural": "reservation rate details",
                "ordering": ["date"],
                "unique_together": {("reservation_room", "date")},
            },
        ),
    ]
