# Generated by Django 4.2.27 on 2026-01-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["check_in_date"], name="reservation_check_i_a5b8d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["check_out_date"], name="reservation_check_o_953303_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["status"], name="reservation_status_f1a03a_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["check_in_date", "check_out_date"],
                name="reservation_check_i_e85e52_idx",
            ),
        ),
    ]
