# Generated by Django 4.2.27 on 2025-12-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(max_length=20, verbose_name="room number"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="room name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VC", "Vacant Clean"),
                            ("VD", "Vacant Dirty"),
                            ("OC", "Occupied Clean"),
                            ("OD", "Occupied Dirty"),
                            ("OOO", "Out of Order"),
                            ("OOS", "Out of Service"),
                        ],
                        default="VC",
                        max_length=5,
                        verbose_name="housekeeping status",
                    ),
                ),
                (
                    "fo_status",
                    models.CharField(
                        choices=[
                            ("VACANT", "Vacant"),
                            ("OCCUPIED", "Occupied"),
                            ("RESERVED", "Reserved"),
                            ("BLOCKED", "Blocked"),
                            ("DUE_OUT", "Due Out"),
                            ("CHECKED_OUT", "Checked Out"),
                        ],
                        default="VACANT",
                        max_length=20,
                        verbose_name="front office status",
                    ),
                ),
                (
                    "is_smoking",
                    models.BooleanField(default=False, verbose_name="smoking allowed"),
                ),
                (
                    "is_accessible",
                    models.BooleanField(default=False, verbose_name="accessible"),
                ),
                (
                    "is_connecting",
                    models.BooleanField(default=False, verbose_name="connecting room"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        to="properties.building",
                    ),
                ),
                (
                    "connecting_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connected_rooms",
                        to="rooms.room",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        to="properties.floor",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
                "ordering": ["hotel", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="RoomAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="amenity name")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="amenity code"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BATHROOM", "Bathroom"),
                            ("BEDROOM", "Bedroom"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("KITCHEN", "Kitchen"),
                            ("TECHNOLOGY", "Technology"),
                            ("COMFORT", "Comfort"),
                            ("VIEW", "View"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="icon"),
                ),
            ],
            options={
                "verbose_name": "room amenity",
                "verbose_name_plural": "room amenities",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="room type name"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, verbose_name="room type code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "max_occupancy",
                    models.PositiveIntegerField(
                        default=2, verbose_name="max occupancy"
                    ),
                ),
                (
                    "max_adults",
                    models.PositiveIntegerField(default=2, verbose_name="max adults"),
                ),
                (
                    "max_children",
                    models.PositiveIntegerField(default=1, verbose_name="max children"),
                ),
                (
                    "size_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="size (sqm)",
                    ),
                ),
                (
                    "bed_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="bed type"
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="base rate",
                    ),
                ),
                (
                    "extra_adult_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="extra adult rate",
                    ),
                ),
                (
                    "extra_child_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="extra child rate",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="room_types/",
                        verbose_name="image",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "room type",
                "verbose_name_plural": "room types",
                "ordering": ["hotel", "sort_order", "name"],
                "unique_together": {("hotel", "code")},
            },
        ),
        migrations.CreateModel(
            name="RoomStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(max_length=5, verbose_name="previous status"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=5, verbose_name="new status"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "room status log",
                "verbose_name_plural": "room status logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RoomBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("MAINTENANCE", "Maintenance"),
                            ("RENOVATION", "Renovation"),
                            ("VIP_BLOCK", "VIP Block"),
                            ("INVENTORY", "Inventory Control"),
                            ("OTHER", "Other"),
                        ],
                        default="MAINTENANCE",
                        max_length=20,
                        verbose_name="reason",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "room block",
                "verbose_name_plural": "room blocks",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="rooms.roomtype",
            ),
        ),
        migrations.CreateModel(
            name="RoomTypeAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="rooms.roomamenity",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="rooms.roomtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "room type amenity",
                "verbose_name_plural": "room type amenities",
                "unique_together": {("room_type", "amenity")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("hotel", "room_number")},
        ),
    ]
