# Generated by Django 4.2.27 on 2026-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_roomimage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["status"], name="rooms_room_status_19affd_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["room_number"], name="rooms_room_room_nu_914a74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["hotel", "status"], name="rooms_room_hotel_i_b263b4_idx"
            ),
        ),
    ]
