# Generated by Django 4.2.27 on 2025-12-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="inspection date",
                    ),
                ),
                (
                    "cleanliness_score",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="cleanliness"
                    ),
                ),
                (
                    "bed_making_score",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="bed making"
                    ),
                ),
                (
                    "bathroom_score",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="bathroom"
                    ),
                ),
                (
                    "amenities_score",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="amenities"
                    ),
                ),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(default=5, verbose_name="overall"),
                ),
                ("passed", models.BooleanField(default=True, verbose_name="passed")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "room inspection",
                "verbose_name_plural": "room inspections",
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="HousekeepingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("CLEANING", "Cleaning"),
                            ("TURNDOWN", "Turndown Service"),
                            ("DEEP_CLEAN", "Deep Cleaning"),
                            ("INSPECTION", "Inspection"),
                            ("LINEN_CHANGE", "Linen Change"),
                            ("AMENITY_REFILL", "Amenity Refill"),
                            ("SPECIAL", "Special Request"),
                        ],
                        default="CLEANING",
                        max_length=20,
                        verbose_name="task type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("INSPECTED", "Inspected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="assigned at"
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="scheduled date"
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="scheduled time"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "inspected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="inspected at"
                    ),
                ),
                (
                    "inspection_notes",
                    models.TextField(blank=True, verbose_name="inspection notes"),
                ),
                (
                    "inspection_passed",
                    models.BooleanField(null=True, verbose_name="passed inspection"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "special_instructions",
                    models.TextField(blank=True, verbose_name="special instructions"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_housekeeping_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_housekeeping_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspected_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housekeeping_tasks",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "housekeeping task",
                "verbose_name_plural": "housekeeping tasks",
                "ordering": ["-scheduled_date", "priority", "room__room_number"],
            },
        ),
        migrations.CreateModel(
            name="LinenInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linen_type",
                    models.CharField(
                        choices=[
                            ("BEDSHEET", "Bed Sheet"),
                            ("DUVET", "Duvet Cover"),
                            ("PILLOW_CASE", "Pillow Case"),
                            ("BATH_TOWEL", "Bath Towel"),
                            ("HAND_TOWEL", "Hand Towel"),
                            ("FACE_TOWEL", "Face Towel"),
                            ("BATH_MAT", "Bath Mat"),
                            ("BATHROBE", "Bathrobe"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "quantity_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total quantity"
                    ),
                ),
                (
                    "quantity_in_use",
                    models.PositiveIntegerField(default=0, verbose_name="in use"),
                ),
                (
                    "quantity_in_laundry",
                    models.PositiveIntegerField(default=0, verbose_name="in laundry"),
                ),
                (
                    "quantity_damaged",
                    models.PositiveIntegerField(default=0, verbose_name="damaged"),
                ),
                (
                    "reorder_level",
                    models.PositiveIntegerField(
                        default=10, verbose_name="reorder level"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linen_inventory",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "linen inventory",
                "verbose_name_plural": "linen inventories",
                "unique_together": {("hotel", "linen_type")},
            },
        ),
        migrations.CreateModel(
            name="HousekeepingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("shift_start", models.TimeField(verbose_name="shift start")),
                ("shift_end", models.TimeField(verbose_name="shift end")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "assigned_floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.floor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housekeeping_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "housekeeping schedule",
                "verbose_name_plural": "housekeeping schedules",
                "ordering": ["date", "shift_start"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="AmenityInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("code", models.CharField(max_length=20, verbose_name="code")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="category"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="quantity"),
                ),
                (
                    "reorder_level",
                    models.PositiveIntegerField(
                        default=10, verbose_name="reorder level"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="unit cost",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_inventory",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "amenity inventory",
                "verbose_name_plural": "amenity inventories",
                "unique_together": {("hotel", "code")},
            },
        ),
    ]
