# Generated by Django 4.2.27 on 2026-02-02 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0002_systemsetting"),
        ("housekeeping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "Receive"),
                            ("ISSUE", "Issue"),
                            ("TRANSFER", "Transfer"),
                            ("ADJUST", "Adjustment"),
                            ("RETURN", "Return"),
                            ("DAMAGE", "Damage"),
                        ],
                        max_length=10,
                        verbose_name="movement type",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="quantity")),
                (
                    "balance_after",
                    models.PositiveIntegerField(verbose_name="balance after"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference"
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="reason"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "from_location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="from location"
                    ),
                ),
                (
                    "to_location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="to location"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "amenity_inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="housekeeping.amenityinventory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linen_inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="housekeeping.lineninventory",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock movement",
                "verbose_name_plural": "stock movements",
                "ordering": ["-created_at"],
            },
        ),
    ]
