# Generated by Django 4.2.30 on 2026-05-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housekeeping", "0002_stockmovement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineninventory",
            name="linen_type",
            field=models.CharField(
                choices=[
                    ("BEDSHEET", "Bed Sheet"),
                    ("DUVET", "Duvet Cover"),
                    ("PILLOW_CASE", "Pillow Case"),
                    ("PILLOW", "Pillow"),
                    ("DUVET_INNER", "Duvet Inner"),
                    ("MATTRESS_PAD", "Mattress Pad"),
                    ("BED_RUNNER", "Bed Runner"),
                    ("BATH_TOWEL", "Bath Towel"),
                    ("HAND_TOWEL", "Hand Towel"),
                    ("FACE_TOWEL", "Face Towel"),
                    ("BATH_MAT", "Bath Mat"),
                    ("BATHROBE", "Bathrobe"),
                    ("POOL_TOWEL", "Pool Towel"),
                    ("GYM_TOWEL", "Gym Towel"),
                    ("TABLE_CLOTH", "Table Cloth"),
                    ("NAPKIN", "Napkin"),
                    ("CHAIR_COVER", "Chair Cover"),
                    ("CURTAIN", "Curtain"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
