# Generated by Django 4.2.30 on 2026-05-14 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0003_alter_lineninventory_linen_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeepingtask',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='scheduled date'),
        ),
    ]
