# Generated by Django 4.2.27 on 2026-01-23 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="device token"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                            ("WEB", "Web"),
                        ],
                        max_length=20,
                        verbose_name="platform",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="device name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="last used"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "push device token",
                "verbose_name_plural": "push device tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
