# Generated by Django 4.2.27 on 2025-12-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rates", "0001_initial"),
        ("properties", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "availability",
                    models.PositiveIntegerField(verbose_name="availability"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("CONFIRMED", "Confirmed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
            ],
            options={
                "verbose_name": "availability update",
                "verbose_name_plural": "availability updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="code"),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("OTA", "Online Travel Agency"),
                            ("GDS", "Global Distribution System"),
                            ("DIRECT", "Direct Booking"),
                            ("META", "Metasearch"),
                            ("CORPORATE", "Corporate Portal"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="commission %",
                    ),
                ),
                ("api_url", models.URLField(blank=True, verbose_name="API URL")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API key"
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API secret"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="channels/",
                        verbose_name="logo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "channel",
                "verbose_name_plural": "channels",
            },
        ),
        migrations.CreateModel(
            name="PropertyChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_code",
                    models.CharField(
                        max_length=100, verbose_name="property code on channel"
                    ),
                ),
                (
                    "rate_markup",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="rate markup %",
                    ),
                ),
                (
                    "min_availability",
                    models.PositiveIntegerField(
                        default=0, verbose_name="min availability"
                    ),
                ),
                (
                    "max_availability",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="max availability"
                    ),
                ),
                (
                    "sync_rates",
                    models.BooleanField(default=True, verbose_name="sync rates"),
                ),
                (
                    "sync_availability",
                    models.BooleanField(default=True, verbose_name="sync availability"),
                ),
                (
                    "sync_restrictions",
                    models.BooleanField(default=True, verbose_name="sync restrictions"),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last sync"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="channels.channel",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="properties.property",
                    ),
                ),
                (
                    "rate_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rates.rateplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "property channel",
                "verbose_name_plural": "property channels",
            },
        ),
        migrations.CreateModel(
            name="RoomTypeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_room_code",
                    models.CharField(max_length=100, verbose_name="channel room code"),
                ),
                (
                    "channel_room_name",
                    models.CharField(max_length=200, verbose_name="channel room name"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "property_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_mappings",
                        to="channels.propertychannel",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.roomtype"
                    ),
                ),
            ],
            options={
                "verbose_name": "room type mapping",
                "verbose_name_plural": "room type mappings",
            },
        ),
        migrations.CreateModel(
            name="RateUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="rate"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("CONFIRMED", "Confirmed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "property_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_updates",
                        to="channels.propertychannel",
                    ),
                ),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rates.rateplan"
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.roomtype"
                    ),
                ),
            ],
            options={
                "verbose_name": "rate update",
                "verbose_name_plural": "rate updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RatePlanMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_rate_code",
                    models.CharField(max_length=100, verbose_name="channel rate code"),
                ),
                (
                    "channel_rate_name",
                    models.CharField(max_length=200, verbose_name="channel rate name"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "property_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_mappings",
                        to="channels.propertychannel",
                    ),
                ),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rates.rateplan"
                    ),
                ),
            ],
            options={
                "verbose_name": "rate plan mapping",
                "verbose_name_plural": "rate plan mappings",
            },
        ),
        migrations.CreateModel(
            name="ChannelReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_booking_id",
                    models.CharField(max_length=100, verbose_name="channel booking ID"),
                ),
                ("raw_data", models.JSONField(default=dict, verbose_name="raw data")),
                (
                    "guest_name",
                    models.CharField(max_length=200, verbose_name="guest name"),
                ),
                ("check_in_date", models.DateField(verbose_name="check in")),
                ("check_out_date", models.DateField(verbose_name="check out")),
                (
                    "room_type_code",
                    models.CharField(max_length=100, verbose_name="room type"),
                ),
                (
                    "rate_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="rate"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processed at"
                    ),
                ),
                (
                    "property_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="channels.propertychannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "channel reservation",
                "verbose_name_plural": "channel reservations",
                "ordering": ["-received_at"],
            },
        ),
    ]
