# Generated by Django 4.2.27 on 2025-12-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        ("rooms", "0001_initial"),
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelreservation",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="availabilityupdate",
            name="property_channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_updates",
                to="channels.propertychannel",
            ),
        ),
        migrations.AddField(
            model_name="availabilityupdate",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rooms.roomtype"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roomtypemapping",
            unique_together={("property_channel", "room_type")},
        ),
        migrations.AlterUniqueTogether(
            name="rateplanmapping",
            unique_together={("property_channel", "rate_plan")},
        ),
        migrations.AlterUniqueTogether(
            name="propertychannel",
            unique_together={("property", "channel")},
        ),
        migrations.AlterUniqueTogether(
            name="channelreservation",
            unique_together={("property_channel", "channel_booking_id")},
        ),
    ]
