# Generated by Django 4.2.27 on 2026-02-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rates", "Rates"),
                            ("availability", "Availability"),
                            ("reservations", "Reservations"),
                            ("restrictions", "Restrictions"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial Success"),
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "records_synced",
                    models.IntegerField(default=0, verbose_name="records synced"),
                ),
                (
                    "error_details",
                    models.TextField(blank=True, verbose_name="error details"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="channels.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "sync log",
                "verbose_name_plural": "sync logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
