# Generated by Django 4.2.30 on 2026-04-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0003_synclog"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertychannel",
            name="webhook_secret",
            field=models.CharField(
                blank=True,
                help_text="Secret key for HMAC webhook signature validation",
                max_length=255,
                verbose_name="webhook secret",
            ),
        ),
    ]
