# Generated by Django 4.2.27 on 2025-12-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashierShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_start", models.DateTimeField(verbose_name="shift start")),
                (
                    "shift_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="shift end"
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="opening balance",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="closing balance",
                    ),
                ),
                (
                    "total_cash_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="cash received",
                    ),
                ),
                (
                    "total_card_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="card received",
                    ),
                ),
                (
                    "is_balanced",
                    models.BooleanField(null=True, verbose_name="balanced"),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="variance",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "cashier shift",
                "verbose_name_plural": "cashier shifts",
                "ordering": ["-shift_start"],
            },
        ),
        migrations.CreateModel(
            name="ChargeCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ROOM", "Room Charge"),
                            ("FOOD", "Food & Beverage"),
                            ("MINIBAR", "Minibar"),
                            ("LAUNDRY", "Laundry"),
                            ("TELEPHONE", "Telephone"),
                            ("PARKING", "Parking"),
                            ("SPA", "Spa & Wellness"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "default_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="default amount",
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(default=True, verbose_name="taxable"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "charge code",
                "verbose_name_plural": "charge codes",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Folio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folio_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="folio number"
                    ),
                ),
                (
                    "folio_type",
                    models.CharField(
                        choices=[
                            ("GUEST", "Guest Folio"),
                            ("MASTER", "Master Folio"),
                            ("GROUP", "Group Folio"),
                            ("COMPANY", "Company Folio"),
                        ],
                        default="GUEST",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("SETTLED", "Settled"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "open_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="open date"
                    ),
                ),
                (
                    "close_date",
                    models.DateField(blank=True, null=True, verbose_name="close date"),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total charges",
                    ),
                ),
                (
                    "total_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total payments",
                    ),
                ),
                (
                    "total_taxes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total taxes",
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, verbose_name="billing address"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="folios",
                        to="guests.company",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="folios",
                        to="guests.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "folio",
                "verbose_name_plural": "folios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="payment number"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("DEBIT_CARD", "Debit Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CITY_LEDGER", "City Ledger"),
                            ("VOUCHER", "Voucher"),
                            ("LOYALTY", "Loyalty Points"),
                        ],
                        max_length=20,
                        verbose_name="method",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="COMPLETED",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="card type"
                    ),
                ),
                (
                    "card_last_four",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="card last 4"
                    ),
                ),
                (
                    "authorization_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="auth code"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "payment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="payment date"
                    ),
                ),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.folio",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="invoice number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="invoice date"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="total"
                    ),
                ),
                (
                    "bill_to_name",
                    models.CharField(max_length=200, verbose_name="bill to name"),
                ),
                (
                    "bill_to_address",
                    models.TextField(blank=True, verbose_name="bill to address"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="billing.folio",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="FolioCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="description"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=8,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="unit price"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="amount"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "charge_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="charge date"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference"
                    ),
                ),
                ("is_posted", models.BooleanField(default=True, verbose_name="posted")),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "charge_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.chargecode",
                    ),
                ),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="billing.folio",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "folio charge",
                "verbose_name_plural": "folio charges",
                "ordering": ["-charge_date", "-posted_at"],
            },
        ),
    ]
