# Generated by Django 4.2.30 on 2026-05-14 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_folio_closed_and_reservation_cancel_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='open_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='open date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='invoice date'),
        ),
    ]
