# Generated by Django 4.2.30 on 2026-05-14 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_folio_open_date_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foliocharge',
            name='charge_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='charge date'),
        ),
    ]
