# Generated by Django 4.2.27 on 2025-12-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("code", models.CharField(max_length=20, verbose_name="code")),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("RACK", "Rack Rate"),
                            ("BAR", "Best Available Rate"),
                            ("CORPORATE", "Corporate Rate"),
                            ("GOVERNMENT", "Government Rate"),
                            ("AAA", "AAA Rate"),
                            ("SENIOR", "Senior Rate"),
                            ("PACKAGE", "Package Rate"),
                            ("PROMOTIONAL", "Promotional Rate"),
                            ("OTA", "OTA Rate"),
                        ],
                        default="BAR",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "min_nights",
                    models.PositiveIntegerField(
                        default=1, verbose_name="minimum nights"
                    ),
                ),
                (
                    "max_nights",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="maximum nights"
                    ),
                ),
                (
                    "min_advance_booking",
                    models.PositiveIntegerField(
                        default=0, verbose_name="min advance days"
                    ),
                ),
                (
                    "max_advance_booking",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="max advance days"
                    ),
                ),
                (
                    "cancellation_policy",
                    models.TextField(blank=True, verbose_name="cancellation policy"),
                ),
                (
                    "cancellation_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="cancellation hours"
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="valid from"),
                ),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="valid to"),
                ),
                (
                    "is_refundable",
                    models.BooleanField(default=True, verbose_name="refundable"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_plans",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "rate plan",
                "verbose_name_plural": "rate plans",
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="YieldRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("OCCUPANCY", "Occupancy Based"),
                            ("DAY_AHEAD", "Days Ahead"),
                            ("DEMAND", "Demand Based"),
                        ],
                        max_length=20,
                        verbose_name="trigger",
                    ),
                ),
                (
                    "min_threshold",
                    models.PositiveIntegerField(verbose_name="min threshold"),
                ),
                (
                    "max_threshold",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="max threshold"
                    ),
                ),
                (
                    "adjustment_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="adjustment %"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="priority"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yield_rules",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "yield rule",
                "verbose_name_plural": "yield rules",
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher priority overrides lower",
                        verbose_name="priority",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "season",
                "verbose_name_plural": "seasons",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("code", models.CharField(max_length=20, verbose_name="code")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "includes_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="includes breakfast"
                    ),
                ),
                (
                    "includes_dinner",
                    models.BooleanField(default=False, verbose_name="includes dinner"),
                ),
                (
                    "includes_spa",
                    models.BooleanField(default=False, verbose_name="includes spa"),
                ),
                (
                    "other_inclusions",
                    models.TextField(blank=True, verbose_name="other inclusions"),
                ),
                (
                    "package_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="package price",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="discount %",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="valid from")),
                ("valid_to", models.DateField(verbose_name="valid to")),
                (
                    "min_nights",
                    models.PositiveIntegerField(
                        default=1, verbose_name="minimum nights"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="properties.property",
                    ),
                ),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="rates.rateplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "package",
                "verbose_name_plural": "packages",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="code"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed Amount"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="value"
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="valid from")),
                ("valid_to", models.DateField(verbose_name="valid to")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="max uses"
                    ),
                ),
                (
                    "times_used",
                    models.PositiveIntegerField(default=0, verbose_name="times used"),
                ),
                (
                    "min_nights",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="min nights"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="min amount",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "discount",
                "verbose_name_plural": "discounts",
            },
        ),
        migrations.CreateModel(
            name="RoomRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "single_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="single rate"
                    ),
                ),
                (
                    "double_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="double rate"
                    ),
                ),
                (
                    "extra_adult",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="extra adult",
                    ),
                ),
                (
                    "extra_child",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="extra child",
                    ),
                ),
                (
                    "sunday_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Sunday",
                    ),
                ),
                (
                    "monday_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monday",
                    ),
                ),
                (
                    "tuesday_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tuesday",
                    ),
                ),
                (
                    "wednesday_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Wednesday",
                    ),
                ),
                (
                    "thursday_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Thursday",
                    ),
                ),
                (
                    "friday_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Friday",
                    ),
                ),
                (
                    "saturday_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Saturday",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_rates",
                        to="rates.rateplan",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="rooms.roomtype",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rates.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "room rate",
                "verbose_name_plural": "room rates",
                "unique_together": {("rate_plan", "room_type", "season")},
            },
        ),
        migrations.CreateModel(
            name="DateRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="rate"
                    ),
                ),
                (
                    "min_stay",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="minimum stay"
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="closed for sale"),
                ),
                (
                    "rate_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rates.rateplan",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_rates",
                        to="rooms.roomtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "date rate",
                "verbose_name_plural": "date rates",
                "unique_together": {("room_type", "rate_plan", "date")},
            },
        ),
    ]
