# Generated by Django 4.2.27 on 2025-12-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="property name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="property code"
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("HOTEL", "Hotel"),
                            ("RESORT", "Resort"),
                            ("MOTEL", "Motel"),
                            ("HOSTEL", "Hostel"),
                            ("APARTMENT", "Apartment"),
                            ("VILLA", "Villa"),
                            ("GUESTHOUSE", "Guest House"),
                        ],
                        default="HOTEL",
                        max_length=20,
                        verbose_name="property type",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="fax"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("address", models.TextField(verbose_name="address")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="country")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "star_rating",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="star rating"
                    ),
                ),
                (
                    "total_rooms",
                    models.PositiveIntegerField(default=0, verbose_name="total rooms"),
                ),
                (
                    "total_floors",
                    models.PositiveIntegerField(default=1, verbose_name="total floors"),
                ),
                (
                    "check_in_time",
                    models.TimeField(default="14:00", verbose_name="check-in time"),
                ),
                (
                    "check_out_time",
                    models.TimeField(default="12:00", verbose_name="check-out time"),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=50, verbose_name="tax ID"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="timezone"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="properties/logos/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="properties/images/",
                        verbose_name="main image",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "property",
                "verbose_name_plural": "properties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="amenity name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("SERVICES", "Services"),
                            ("DINING", "Dining"),
                            ("RECREATION", "Recreation"),
                            ("BUSINESS", "Business"),
                            ("WELLNESS", "Wellness"),
                            ("ACCESSIBILITY", "Accessibility"),
                        ],
                        default="GENERAL",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="icon"),
                ),
                (
                    "is_chargeable",
                    models.BooleanField(default=False, verbose_name="chargeable"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "property amenity",
                "verbose_name_plural": "property amenities",
                "ordering": ["property", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="building name"),
                ),
                ("code", models.CharField(max_length=20, verbose_name="building code")),
                (
                    "floors",
                    models.PositiveIntegerField(
                        default=1, verbose_name="number of floors"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "building",
                "verbose_name_plural": "buildings",
                "ordering": ["property", "name"],
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="TaxConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="tax name")),
                ("code", models.CharField(max_length=20, verbose_name="tax code")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="rate (%)"
                    ),
                ),
                (
                    "is_percentage",
                    models.BooleanField(default=True, verbose_name="is percentage"),
                ),
                (
                    "applies_to_room",
                    models.BooleanField(default=True, verbose_name="applies to room"),
                ),
                (
                    "applies_to_services",
                    models.BooleanField(
                        default=True, verbose_name="applies to services"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "tax configuration",
                "verbose_name_plural": "tax configurations",
                "unique_together": {("property", "code")},
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="floor number")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="floor name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_floors",
                        to="properties.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "floor",
                "verbose_name_plural": "floors",
                "ordering": ["building", "number"],
                "unique_together": {("building", "number")},
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="department name"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, verbose_name="department code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "ordering": ["property", "name"],
                "unique_together": {("property", "code")},
            },
        ),
    ]
