# Generated by Django 4.2.27 on 2026-01-23 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="language"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="timezone"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="YYYY-MM-DD", max_length=20, verbose_name="date format"
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        default="HH:mm", max_length=20, verbose_name="time format"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=20,
                        verbose_name="theme",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="email notifications"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="push notifications"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="SMS notifications"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="tax rate",
                    ),
                ),
                (
                    "service_charge_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="service charge rate",
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(default="14:00", verbose_name="check-in time"),
                ),
                (
                    "check_out_time",
                    models.TimeField(default="11:00", verbose_name="check-out time"),
                ),
                (
                    "extra_settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="extra settings"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "property",
                    models.OneToOneField(
                        blank=True,
                        help_text="Leave blank for system-wide settings",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "system setting",
                "verbose_name_plural": "system settings",
            },
        ),
    ]
