# Generated by Django 4.2.30 on 2026-05-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_systemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='property code'),
        ),
    ]
