# Generated by Django 4.2.27 on 2025-12-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="company name")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="company code"
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("CORPORATE", "Corporate"),
                            ("TRAVEL_AGENT", "Travel Agent"),
                            ("OTA", "OTA"),
                            ("TOUR_OPERATOR", "Tour Operator"),
                            ("GOVERNMENT", "Government"),
                            ("OTHER", "Other"),
                        ],
                        default="CORPORATE",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contact person"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="fax"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=50, verbose_name="tax ID"),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="credit limit",
                    ),
                ),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        default=30, verbose_name="payment terms (days)"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="discount %",
                    ),
                ),
                (
                    "contract_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="contract start"
                    ),
                ),
                (
                    "contract_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="contract end"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=20, verbose_name="title"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="middle name"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nationality"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="phone")),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="mobile"),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="fax"),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=100, verbose_name="state"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "id_type",
                    models.CharField(blank=True, max_length=50, verbose_name="ID type"),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID number"
                    ),
                ),
                (
                    "id_expiry",
                    models.DateField(blank=True, null=True, verbose_name="ID expiry"),
                ),
                (
                    "id_issuing_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID issuing country"
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="passport number"
                    ),
                ),
                (
                    "guest_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("CORPORATE", "Corporate"),
                            ("VIP", "VIP"),
                            ("LOYALTY", "Loyalty Member"),
                        ],
                        default="INDIVIDUAL",
                        max_length=20,
                        verbose_name="guest type",
                    ),
                ),
                (
                    "vip_level",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="VIP level"
                    ),
                ),
                (
                    "loyalty_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="loyalty number",
                    ),
                ),
                (
                    "loyalty_tier",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="loyalty tier"
                    ),
                ),
                (
                    "loyalty_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="loyalty points"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="preferred language"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="guests/", verbose_name="photo"
                    ),
                ),
                (
                    "is_blacklisted",
                    models.BooleanField(default=False, verbose_name="blacklisted"),
                ),
                (
                    "blacklist_reason",
                    models.TextField(blank=True, verbose_name="blacklist reason"),
                ),
                (
                    "total_stays",
                    models.PositiveIntegerField(default=0, verbose_name="total stays"),
                ),
                (
                    "total_nights",
                    models.PositiveIntegerField(default=0, verbose_name="total nights"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total revenue",
                    ),
                ),
                (
                    "last_stay_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="last stay date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guests",
                        to="guests.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "guest",
                "verbose_name_plural": "guests",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="program name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "points_per_currency",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        verbose_name="points per currency unit",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_programs",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "loyalty program",
                "verbose_name_plural": "loyalty programs",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("EARN", "Earn"),
                            ("REDEEM", "Redeem"),
                            ("ADJUST", "Adjustment"),
                            ("EXPIRE", "Expiration"),
                        ],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="points")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="description"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference"
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(verbose_name="balance after"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_transactions",
                        to="guests.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "loyalty transaction",
                "verbose_name_plural": "loyalty transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="tier name")),
                (
                    "min_points",
                    models.PositiveIntegerField(verbose_name="minimum points"),
                ),
                ("benefits", models.TextField(blank=True, verbose_name="benefits")),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="discount %",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="guests.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "loyalty tier",
                "verbose_name_plural": "loyalty tiers",
                "ordering": ["min_points"],
            },
        ),
        migrations.CreateModel(
            name="GuestPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ROOM", "Room"),
                            ("PILLOW", "Pillow"),
                            ("FOOD", "Food"),
                            ("BEVERAGE", "Beverage"),
                            ("NEWSPAPER", "Newspaper"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "preference",
                    models.CharField(max_length=200, verbose_name="preference"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="guests.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "guest preference",
                "verbose_name_plural": "guest preferences",
            },
        ),
        migrations.CreateModel(
            name="GuestDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PASSPORT", "Passport"),
                            ("ID_CARD", "ID Card"),
                            ("DRIVER_LICENSE", "Driver License"),
                            ("VISA", "Visa"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="document type",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="document number"),
                ),
                (
                    "issuing_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="issuing country"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(blank=True, null=True, verbose_name="issue date"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="expiry date"),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="guest_documents/",
                        verbose_name="document file",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="guests.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "guest document",
                "verbose_name_plural": "guest documents",
            },
        ),
    ]
