# Generated by Django - Custom migration for performance indexes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['email'], name='guests_guest_email_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['phone'], name='guests_guest_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['last_name', 'first_name'], name='guests_guest_name_idx'),
        ),
    ]
