# Generated by Django 4.2.27 on 2026-01-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0002_guest_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="guest",
            new_name="guests_gues_email_e4fe59_idx",
            old_name="guests_guest_email_idx",
        ),
        migrations.RenameIndex(
            model_name="guest",
            new_name="guests_gues_phone_6b6426_idx",
            old_name="guests_guest_phone_idx",
        ),
        migrations.RenameIndex(
            model_name="guest",
            new_name="guests_gues_last_na_682095_idx",
            old_name="guests_guest_name_idx",
        ),
    ]
