# Generated by Django 4.2.27 on 2026-02-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "guests",
            "0003_rename_guests_guest_email_idx_guests_gues_email_e4fe59_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestdocument",
            options={
                "ordering": ["-issue_date"],
                "verbose_name": "guest document",
                "verbose_name_plural": "guest documents",
            },
        ),
    ]
