# Generated by Django 4.2.30 on 2026-05-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_systemsetting"),
        ("guests", "0004_alter_guestdocument_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="home_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guests",
                to="properties.property",
                verbose_name="property",
            ),
        ),
    ]
