# Generated by Django 4.2.30 on 2026-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_accounts_us_email_74c8d6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_codes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="One-time recovery codes",
                verbose_name="backup codes",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(default=False, verbose_name="MFA enabled"),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TOTP", "Authenticator App"),
                    ("EMAIL", "Email Code"),
                    ("SMS", "SMS Code"),
                ],
                default="TOTP",
                max_length=10,
                verbose_name="MFA method",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_secret",
            field=models.CharField(
                blank=True,
                help_text="TOTP secret for Google Authenticator",
                max_length=32,
                verbose_name="MFA secret",
            ),
        ),
    ]
