# Generated by Django 4.2.27 on 2025-12-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Report"),
                            ("OCCUPANCY", "Occupancy Report"),
                            ("REVENUE", "Revenue Report"),
                            ("ARRIVAL", "Arrival Report"),
                            ("DEPARTURE", "Departure Report"),
                            ("IN_HOUSE", "In-House Guest List"),
                            ("HOUSEKEEPING", "Housekeeping Report"),
                            ("RESERVATION", "Reservation Report"),
                            ("PRODUCTION", "Production Report"),
                            ("AUDIT", "Night Audit Report"),
                            ("FORECAST", "Forecast Report"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "config",
                    models.JSONField(default=dict, verbose_name="configuration"),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(default=False, verbose_name="scheduled"),
                ),
                (
                    "schedule_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="schedule time"
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(blank=True, verbose_name="email recipients"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "report template",
                "verbose_name_plural": "report templates",
            },
        ),
        migrations.CreateModel(
            name="NightAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_date", models.DateField(verbose_name="business date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "no_shows_processed",
                    models.BooleanField(
                        default=False, verbose_name="no-shows processed"
                    ),
                ),
                (
                    "room_rates_posted",
                    models.BooleanField(
                        default=False, verbose_name="room rates posted"
                    ),
                ),
                (
                    "folios_settled",
                    models.BooleanField(default=False, verbose_name="folios settled"),
                ),
                (
                    "departures_checked",
                    models.BooleanField(
                        default=False, verbose_name="departures checked"
                    ),
                ),
                (
                    "room_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="room revenue",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "fb_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="F&B revenue",
                    ),
                ),
                (
                    "other_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="other revenue",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total revenue",
                    ),
                ),
                (
                    "payments_collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="payments collected",
                    ),
                ),
                (
                    "rooms_sold",
                    models.PositiveIntegerField(default=0, verbose_name="rooms sold"),
                ),
                (
                    "arrivals_count",
                    models.PositiveIntegerField(default=0, verbose_name="arrivals"),
                ),
                (
                    "departures_count",
                    models.PositiveIntegerField(default=0, verbose_name="departures"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="night_audits",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "night audit",
                "verbose_name_plural": "night audits",
                "ordering": ["-business_date"],
                "unique_together": {("property", "business_date")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(max_length=100, verbose_name="step")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "is_error",
                    models.BooleanField(default=False, verbose_name="is error"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "night_audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="reports.nightaudit",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="year")),
                ("month", models.PositiveIntegerField(verbose_name="month")),
                (
                    "avg_occupancy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="avg occupancy",
                    ),
                ),
                (
                    "avg_adr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="avg ADR",
                    ),
                ),
                (
                    "avg_revpar",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="avg RevPAR",
                    ),
                ),
                (
                    "total_room_nights",
                    models.PositiveIntegerField(default=0, verbose_name="room nights"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total revenue",
                    ),
                ),
                (
                    "room_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="room revenue",
                    ),
                ),
                (
                    "fb_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="F&B revenue",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_stats",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "monthly statistics",
                "verbose_name_plural": "monthly statistics",
                "ordering": ["-year", "-month"],
                "unique_together": {("property", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="DailyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "total_rooms",
                    models.PositiveIntegerField(default=0, verbose_name="total rooms"),
                ),
                (
                    "rooms_sold",
                    models.PositiveIntegerField(default=0, verbose_name="rooms sold"),
                ),
                (
                    "rooms_ooo",
                    models.PositiveIntegerField(
                        default=0, verbose_name="rooms out of order"
                    ),
                ),
                (
                    "available_rooms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="available rooms"
                    ),
                ),
                (
                    "complimentary_rooms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="complimentary rooms"
                    ),
                ),
                (
                    "house_use_rooms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="house use rooms"
                    ),
                ),
                (
                    "occupancy_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="occupancy %",
                    ),
                ),
                (
                    "room_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="room revenue",
                    ),
                ),
                (
                    "fb_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="F&B revenue",
                    ),
                ),
                (
                    "other_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="other revenue",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total revenue",
                    ),
                ),
                (
                    "adr",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="ADR"
                    ),
                ),
                (
                    "revpar",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="RevPAR",
                    ),
                ),
                (
                    "arrivals",
                    models.PositiveIntegerField(default=0, verbose_name="arrivals"),
                ),
                (
                    "departures",
                    models.PositiveIntegerField(default=0, verbose_name="departures"),
                ),
                (
                    "in_house",
                    models.PositiveIntegerField(
                        default=0, verbose_name="in house guests"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily statistics",
                "verbose_name_plural": "daily statistics",
                "ordering": ["-date"],
                "unique_together": {("property", "date")},
            },
        ),
    ]
